const MODULES = {
  core: [
    'AccountSettings',
    'ActivityStream',
    'Attachments',
    'Automations',
    'Brand',
    'Categories',
    'CustomAgentRoles',
    'DynamicContent',
    'Forums',
    'ForumSubscriptions',
    'GroupMemberships',
    'Groups',
    'Imports',
    'Installations',
    'JobStatuses',
    'Locales',
    'Macros',
    'OauthTokens',
    'OrganizationFields',
    'OrganizationMemberships',
    'Organizations',
    'PermissionGroups',
    'Policies',
    'Requests',
    'SatisfactionRatings',
    'Search',
    'Sessions',
    'SharingAgreement',
    'SuspendedTickets',
    'Tags',
    'Targets',
    'TicketAudits',
    'TicketEvents',
    'TicketExport',
    'TicketFields',
    'TicketForms',
    'TicketImport',
    'TicketMetrics',
    'Tickets',
    'TopicComments',
    'Topics',
    'TopicSubscriptions',
    'TopicVotes',
    'Triggers',
    'UserFields',
    'UserIdentities',
    'Users',
    'Views',
    'Webhooks',
  ],
  helpcenter: [
    'AccessPolicies',
    'ArticleAttachments',
    'ArticleComments',
    'ArticleLabels',
    'Articles',
    'Categories',
    'Search',
    'Sections',
    'Subscriptions',
    'Translations',
    'UserSegments',
    'Votes',
  ],
  nps: ['Invitations', 'Surveys'],
  services: ['Links'],
  voice: [
    'AgentActivity',
    'Availabilities',
    'CurrentQueueActivity',
    'GreetingCategories',
    'Greetings',
    'HistoricalQueueActivity',
    'PhoneNumbers',
  ],
};

const ENDPOINTS = {
  core: '.zendesk.com/api/v2',
  helpcenter: '.zendesk.com/api/v2/help_center',
  services: '.zendesk.com/api/services/jira',
  voice: '.zendesk.com/api/v2/channels/voice',
};

const MOCK_API = (['development', 'test'].includes(process.env.NODE_ENV));

module.exports = {MODULES, ENDPOINTS, MOCK_API};
